In [44]:
import pandas as pd

df = pd.read_csv("pharma-data.csv",)

print(df.shape)
print(df.head())
# print(df.info())

(254082, 23)
   Unnamed: 0.1  Unnamed: 0             Distributor  \
0             0           0  Gottlieb-Cruickshank
1             1           1  Gottlieb-Cruickshank
2             2           2  Gottlieb-Cruickshank
3             3           3  Gottlieb-Cruickshank
4             4           4  Gottlieb-Cruickshank

                          Customer Name     City Country  Latitude  Longitude  \
0               Zieme, Doyle and Kunze    Lublin  Poland   51.2333    22.5667
1                            Feest PLC   Świecie  Poland   53.4167    18.4333
2  Medhurst-Beer Pharmaceutical Limited   Rybnik  Poland   50.0833    18.5000
3                 Barton Ltd Pharma Plc  Czeladź  Poland   50.3333    19.0833
4                  Keeling LLC Pharmacy  Olsztyn  Poland   53.7800    20.4942

    Channel  Sub-channel  ... Price   Sales    Month  Year  Name of Sales Rep  \
0  Hospital      Private  ...   368  1472.0  January  2018       Mary Gerrard
1  Pharmacy       Retail  ...   591  4137.0  January  2018      Jessica Smith
2  Pharmacy  Institution  ...    66  1980.0  January  2018       Steve Pepple
3  Hospital      Private  ...   435  2610.0  January  2018       Mary Gerrard
4  Pharmacy       Retail  ...   458  9160.0  January  2018            Anne Wu

         Manager  Sales Team      Sales Rep Month_Num        Date
0  Britanny Bold       Delta   Mary Gerrard         1  2018-01-01
1  Britanny Bold       Delta  Jessica Smith         1  2018-01-01
2    Tracy Banks       Bravo   Steve Pepple         1  2018-01-01
3  Britanny Bold       Delta   Mary Gerrard         1  2018-01-01
4  Britanny Bold       Delta        Anne Wu         1  2018-01-01

[5 rows x 23 columns]

In [45]:
df['Sales Rep']=df['Name of Sales Rep']

In [46]:
df

,Unnamed: 0.1,Unnamed: 0,Distributor,Customer Name,City,Country,Latitude,Longitude,Channel,Sub-channel,...,Price,Sales,Month,Year,Name of Sales Rep,Manager,Sales Team,Sales Rep,Month_Num,Date
0,0,0,Gottlieb-Cruickshank,"Zieme, Doyle and Kunze",Lublin,Poland,51.2333,22.5667,Hospital,Private,...,368,1472.0,January,2018,Mary Gerrard,Britanny Bold,Delta,Mary Gerrard,1,2018-01-01
1,1,1,Gottlieb-Cruickshank,Feest PLC,Świecie,Poland,53.4167,18.4333,Pharmacy,Retail,...,591,4137.0,January,2018,Jessica Smith,Britanny Bold,Delta,Jessica Smith,1,2018-01-01
2,2,2,Gottlieb-Cruickshank,Medhurst-Beer Pharmaceutical Limited,Rybnik,Poland,50.0833,18.5000,Pharmacy,Institution,...,66,1980.0,January,2018,Steve Pepple,Tracy Banks,Bravo,Steve Pepple,1,2018-01-01
3,3,3,Gottlieb-Cruickshank,Barton Ltd Pharma Plc,Czeladź,Poland,50.3333,19.0833,Hospital,Private,...,435,2610.0,January,2018,Mary Gerrard,Britanny Bold,Delta,Mary Gerrard,1,2018-01-01
4,4,4,Gottlieb-Cruickshank,Keeling LLC Pharmacy,Olsztyn,Poland,53.7800,20.4942,Pharmacy,Retail,...,458,9160.0,January,2018,Anne Wu,Britanny Bold,Delta,Anne Wu,1,2018-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254077,254077,254077,Bashirian-Kassulke,"Koch, Borer and Hagenes Pharmaceutical Ltd",Lauf,Germany,49.5103,11.2772,Hospital,Private,...,497,456743.0,December,2020,Thompson Crawford,James Goodwill,Alfa,Thompson Crawford,12,2020-12-01
254078,254078,254078,Bashirian-Kassulke,Hane Ltd Pharmaceutical Ltd,Aichach,Germany,48.4500,11.1333,Hospital,Private,...,681,294192.0,December,2020,Anne Wu,Britanny Bold,Delta,Anne Wu,12,2020-12-01
254079,254079,254079,Bashirian-Kassulke,Harris-Conroy Pharmacy,Wilhelmshaven,Germany,53.5167,8.1333,Pharmacy,Retail,...,678,216960.0,December,2020,Abigail Thompson,Tracy Banks,Bravo,Abigail Thompson,12,2020-12-01
254080,254080,254080,Bashirian-Kassulke,Balistreri Group Pharm,Böblingen,Germany,48.6833,9.0000,Hospital,Government,...,115,64975.0,December,2020,Stella Given,Alisha Cordwell,Charlie,Stella Given,12,2020-12-01
254081,254081,254081,Bashirian-Kassulke,"Heathcote, Kovacek and Parker",Hof,Germany,50.3167,11.9167,Pharmacy,Retail,...,115,124200.0,December,2020,Alan Ray,James Goodwill,Alfa,Alan Ray,12,2020-12-01

In [47]:
total_sales = df["Sales"].sum()

total_quantity = df["Quantity"].sum()

total_customers = df["Customer Name"].nunique()

total_products = df["Product Name"].nunique()

total_distributors = df["Distributor"].nunique()

print(f"Total Sales: {total_sales:,.2f}")
print(f"Total Quantity: {total_quantity:,}")
print(f"Total Customers: {total_customers}")
print(f"Total Products: {total_products}")
print(f"Total Distributors: {total_distributors}")

Total Sales: 11,798,987,642.20
Total Quantity: 28,678,778.802551232
Total Customers: 751
Total Products: 240
Total Distributors: 29

In [48]:
monthly_sales = (
    df.groupby(["Year","Month"])["Sales"]
      .sum()
      .reset_index()
)

monthly_sales.head(5)

   Year     Month        Sales
0  2017     April  188800584.0
1  2017    August  233834675.0
2  2017  December  220759542.0
3  2017  February  208995889.0
4  2017   January  151872184.0

In [49]:
df

,Unnamed: 0.1,Unnamed: 0,Distributor,Customer Name,City,Country,Latitude,Longitude,Channel,Sub-channel,...,Price,Sales,Month,Year,Name of Sales Rep,Manager,Sales Team,Sales Rep,Month_Num,Date
0,0,0,Gottlieb-Cruickshank,"Zieme, Doyle and Kunze",Lublin,Poland,51.2333,22.5667,Hospital,Private,...,368,1472.0,January,2018,Mary Gerrard,Britanny Bold,Delta,Mary Gerrard,1,2018-01-01
1,1,1,Gottlieb-Cruickshank,Feest PLC,Świecie,Poland,53.4167,18.4333,Pharmacy,Retail,...,591,4137.0,January,2018,Jessica Smith,Britanny Bold,Delta,Jessica Smith,1,2018-01-01
2,2,2,Gottlieb-Cruickshank,Medhurst-Beer Pharmaceutical Limited,Rybnik,Poland,50.0833,18.5000,Pharmacy,Institution,...,66,1980.0,January,2018,Steve Pepple,Tracy Banks,Bravo,Steve Pepple,1,2018-01-01
3,3,3,Gottlieb-Cruickshank,Barton Ltd Pharma Plc,Czeladź,Poland,50.3333,19.0833,Hospital,Private,...,435,2610.0,January,2018,Mary Gerrard,Britanny Bold,Delta,Mary Gerrard,1,2018-01-01
4,4,4,Gottlieb-Cruickshank,Keeling LLC Pharmacy,Olsztyn,Poland,53.7800,20.4942,Pharmacy,Retail,...,458,9160.0,January,2018,Anne Wu,Britanny Bold,Delta,Anne Wu,1,2018-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254077,254077,254077,Bashirian-Kassulke,"Koch, Borer and Hagenes Pharmaceutical Ltd",Lauf,Germany,49.5103,11.2772,Hospital,Private,...,497,456743.0,December,2020,Thompson Crawford,James Goodwill,Alfa,Thompson Crawford,12,2020-12-01
254078,254078,254078,Bashirian-Kassulke,Hane Ltd Pharmaceutical Ltd,Aichach,Germany,48.4500,11.1333,Hospital,Private,...,681,294192.0,December,2020,Anne Wu,Britanny Bold,Delta,Anne Wu,12,2020-12-01
254079,254079,254079,Bashirian-Kassulke,Harris-Conroy Pharmacy,Wilhelmshaven,Germany,53.5167,8.1333,Pharmacy,Retail,...,678,216960.0,December,2020,Abigail Thompson,Tracy Banks,Bravo,Abigail Thompson,12,2020-12-01
254080,254080,254080,Bashirian-Kassulke,Balistreri Group Pharm,Böblingen,Germany,48.6833,9.0000,Hospital,Government,...,115,64975.0,December,2020,Stella Given,Alisha Cordwell,Charlie,Stella Given,12,2020-12-01
254081,254081,254081,Bashirian-Kassulke,"Heathcote, Kovacek and Parker",Hof,Germany,50.3167,11.9167,Pharmacy,Retail,...,115,124200.0,December,2020,Alan Ray,James Goodwill,Alfa,Alan Ray,12,2020-12-01

In [50]:
product_monthly_sales = (
    df.groupby(["Product Name", "Year", "Month"])["Sales"]
      .sum()
      .reset_index()
      .sort_values("Sales",ascending=False)
)
product_monthly_sales.to_csv("product_monthly_sales.csv")

In [51]:
product_sales = (
    df.groupby(["Product Name","Month","Year","Channel","Sub-channel"])["Sales"]
      .sum()
      .reset_index()
      .sort_values("Sales",ascending=False)
)
product_sales

               Product Name     Month  Year   Channel Sub-channel       Sales
25326            Ionclotide    August  2019  Pharmacy      Retail  74437808.0
40865            Tetratanyl   October  2020  Pharmacy      Retail  47052880.0
8778     Antaparin Varizyme    August  2019  Pharmacy      Retail  30261870.0
7255              Amavirase    August  2019  Pharmacy      Retail  28545018.0
40732            Tetratanyl  December  2019  Hospital  Government  25596501.0
...                     ...       ...   ...       ...         ...         ...
43747              Victomax    August  2018  Hospital  Government  -1323252.0
12484  Ceftatana Serolamide      June  2020  Hospital  Government  -1342915.0
24553  Interfeferon Aspipex     April  2020  Hospital  Government  -1393600.0
25630       Ketamara Evogel       May  2020  Hospital     Private  -2925120.0
16011      Dantolac Pazocor    August  2019  Hospital     Private  -4141370.0

[45621 rows x 6 columns]

In [52]:
product_sales.head(10)

             Product Name     Month  Year   Channel  Sub-channel       Sales
25326          Ionclotide    August  2019  Pharmacy       Retail  74437808.0
40865          Tetratanyl   October  2020  Pharmacy       Retail  47052880.0
8778   Antaparin Varizyme    August  2019  Pharmacy       Retail  30261870.0
7255            Amavirase    August  2019  Pharmacy       Retail  28545018.0
40732          Tetratanyl  December  2019  Hospital   Government  25596501.0
38650          Sumanazole  December  2020  Pharmacy       Retail  24583688.0
39194           Symbitrim    August  2019  Hospital   Government  23696560.0
38611          Sumanazole     April  2019  Hospital   Government  21637158.0
15701          Cyclovital      July  2020  Pharmacy  Institution  21204994.0
33915         Propratecan  February  2019  Hospital   Government  20632546.0

In [53]:
class_sales = (
    df.groupby("Product Class")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

class_sales

Product Class
Analgesics          2.371515e+09
Antiseptics         2.237525e+09
Mood Stabilizers    2.058910e+09
Antipiretics        1.883306e+09
Antibiotics         1.750277e+09
Antimalarial        1.497455e+09
Name: Sales, dtype: float64

In [54]:
rep_sales = (
    df.groupby("Sales Rep")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

rep_sales

Sales Rep
Jimmy Grey           9.859700e+08
Abigail Thompson     9.810570e+08
Sheila Stones        9.582039e+08
Daniel Gates         9.506586e+08
Anne Wu              9.201683e+08
Morris Garcia        9.011955e+08
Stella Given         8.883409e+08
Jessica Smith        8.816984e+08
Steve Pepple         8.754500e+08
Mary Gerrard         8.752708e+08
Erica Jones          8.713722e+08
Thompson Crawford    8.669649e+08
Alan Ray             8.426372e+08
Name: Sales, dtype: float64

In [55]:
manager_sales = (
    df.groupby("Manager")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

manager_sales

Manager
Britanny Bold      3.635341e+09
Alisha Cordwell    2.824970e+09
Tracy Banks        2.757702e+09
James Goodwill     2.580974e+09
Name: Sales, dtype: float64

In [56]:
city_product = (
    df.groupby(["City", "Product Name"])["Sales"]
      .sum()
      .reset_index()
)

top_product_city = (
    city_product.sort_values(["City", "Sales"], ascending=[True, False])
                .groupby("City")
                .head(1)
)

top_product_city

               City           Product Name      Sales
179          Aachen           Topifribrate  2912490.0
315           Aalen               Lovepion   773568.0
410          Achern           Alglutriptan  1996533.0
705           Achim               Menogine  3160920.0
897           Ahaus  Microroban Afatigomar  2335508.0
...             ...                    ...        ...
132219      Świecie               Diaxolol   191250.0
132406  Świedbodzin               Sevoderm  1432080.0
132536  Świnoujście              Symbitrim  1361440.0
132632         Żary   Halcifergen Nevazone   538180.0
132729      Żychlin    Argalazine Abostryl   813888.0

[749 rows x 3 columns]

In [57]:
top_product_city.to_csv("top_product_city.csv",index=False)

In [58]:
city_sales = (
    df.groupby("City")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

city_sales.head(20)

City
Butzbach          9.356178e+07
Baesweiler        6.489050e+07
Cuxhaven          5.600668e+07
Friedberg         5.218363e+07
Altenburg         5.088532e+07
Emsdetten         4.593901e+07
Bottrop           4.445462e+07
Freising          4.377938e+07
Trier             4.349563e+07
Castrop-Rauxel    4.206666e+07
Limburg           4.151422e+07
Berlin            4.079679e+07
Wedel             4.046475e+07
Ditzingen         4.035582e+07
Dachau            3.793555e+07
Eberswalde        3.746560e+07
Springe           3.718111e+07
Weinheim          3.703776e+07
Filderstadt       3.676729e+07
Dessau-Roßlau     3.647921e+07
Name: Sales, dtype: float64

In [59]:
distributor_sales = (
    df.groupby("Distributor")["Sales"]
      .sum()
      .sort_values(ascending=False)
)
distributor_sales.head(20)

Distributor
Gerlach LLC               3.501834e+09
Koss                      3.087827e+09
Erdman                    1.522610e+09
Kozey-Emmerich            1.232932e+09
Romaguera-Fay             4.449925e+08
Bashirian-Kassulke        3.493407e+08
Welch-Langworth           2.606324e+08
Daugherty-Rempel          2.321302e+08
Beier                     1.508344e+08
Rohan and Sons            1.425120e+08
Gleason                   1.386184e+08
Stehr-Champlin            1.285149e+08
Smith Inc                 1.195473e+08
Lockman                   9.598333e+07
Prohaska-Kuhic            8.198061e+07
Cassin                    5.865607e+07
Gottlieb-Cruickshank      4.797586e+07
Crist Inc                 4.505648e+07
Rohan                     3.174573e+07
Nader-Gaylord             2.709206e+07
Name: Sales, dtype: float64

In [60]:
channel_sales = (
    df.groupby("Channel")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

channel_sales

Channel
Pharmacy    6.218312e+09
Hospital    5.580676e+09
Name: Sales, dtype: float64

In [61]:
monthly_sales.to_csv("monthly_sales.csv", index=False)

product_sales.to_csv("product_sales.csv")

rep_sales.to_csv("rep_sales.csv")

city_sales.to_csv("city_sales.csv")

channel_sales.to_csv("channel_sales.csv")

In [62]:
df

,Unnamed: 0.1,Unnamed: 0,Distributor,Customer Name,City,Country,Latitude,Longitude,Channel,Sub-channel,...,Price,Sales,Month,Year,Name of Sales Rep,Manager,Sales Team,Sales Rep,Month_Num,Date
0,0,0,Gottlieb-Cruickshank,"Zieme, Doyle and Kunze",Lublin,Poland,51.2333,22.5667,Hospital,Private,...,368,1472.0,January,2018,Mary Gerrard,Britanny Bold,Delta,Mary Gerrard,1,2018-01-01
1,1,1,Gottlieb-Cruickshank,Feest PLC,Świecie,Poland,53.4167,18.4333,Pharmacy,Retail,...,591,4137.0,January,2018,Jessica Smith,Britanny Bold,Delta,Jessica Smith,1,2018-01-01
2,2,2,Gottlieb-Cruickshank,Medhurst-Beer Pharmaceutical Limited,Rybnik,Poland,50.0833,18.5000,Pharmacy,Institution,...,66,1980.0,January,2018,Steve Pepple,Tracy Banks,Bravo,Steve Pepple,1,2018-01-01
3,3,3,Gottlieb-Cruickshank,Barton Ltd Pharma Plc,Czeladź,Poland,50.3333,19.0833,Hospital,Private,...,435,2610.0,January,2018,Mary Gerrard,Britanny Bold,Delta,Mary Gerrard,1,2018-01-01
4,4,4,Gottlieb-Cruickshank,Keeling LLC Pharmacy,Olsztyn,Poland,53.7800,20.4942,Pharmacy,Retail,...,458,9160.0,January,2018,Anne Wu,Britanny Bold,Delta,Anne Wu,1,2018-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254077,254077,254077,Bashirian-Kassulke,"Koch, Borer and Hagenes Pharmaceutical Ltd",Lauf,Germany,49.5103,11.2772,Hospital,Private,...,497,456743.0,December,2020,Thompson Crawford,James Goodwill,Alfa,Thompson Crawford,12,2020-12-01
254078,254078,254078,Bashirian-Kassulke,Hane Ltd Pharmaceutical Ltd,Aichach,Germany,48.4500,11.1333,Hospital,Private,...,681,294192.0,December,2020,Anne Wu,Britanny Bold,Delta,Anne Wu,12,2020-12-01
254079,254079,254079,Bashirian-Kassulke,Harris-Conroy Pharmacy,Wilhelmshaven,Germany,53.5167,8.1333,Pharmacy,Retail,...,678,216960.0,December,2020,Abigail Thompson,Tracy Banks,Bravo,Abigail Thompson,12,2020-12-01
254080,254080,254080,Bashirian-Kassulke,Balistreri Group Pharm,Böblingen,Germany,48.6833,9.0000,Hospital,Government,...,115,64975.0,December,2020,Stella Given,Alisha Cordwell,Charlie,Stella Given,12,2020-12-01
254081,254081,254081,Bashirian-Kassulke,"Heathcote, Kovacek and Parker",Hof,Germany,50.3167,11.9167,Pharmacy,Retail,...,115,124200.0,December,2020,Alan Ray,James Goodwill,Alfa,Alan Ray,12,2020-12-01

In [63]:
top_managers=(df.groupby("Manager")['Sales'].sum().sort_values(ascending=False))
top_managers.to_csv("top_manager.csv")

In [64]:
top_sales_rep=(df.groupby(["Sales Rep","Manager","Year","Month"])['Sales'].sum().reset_index().sort_values("Sales",ascending=False))
top_sales_rep.to_csv("top_sales_rep.csv")

In [65]:
top_sales_rep.to_csv("top_sales_rep.csv")

In [68]:
top_dist = (
    df.groupby(["Distributor","Product Name"])["Sales"]
      .sum()
      .reset_index()
      .sort_values("Sales",ascending=False)
)
top_dist.to_csv("top_dist.csv")

In [ ]:
year_sales = (
    df.groupby(["Year","Month"])["Sales"]
      .sum()
      .reset_index()
      .sort_values("Sales",ascending=False)
)
year_sales.to_csv("year_t_sales.csv")

In [ ]:
product_revenue = (
    df.groupby("Product Name")["Sales"]
      .sum()
      .reset_index()
      .sort_values("Sales", ascending=False)
)

product_revenue["Revenue_%"] = (
    product_revenue["Sales"]
    / product_revenue["Sales"].sum()
    * 100
)

product_revenue["Cum_%"] = (
    product_revenue["Revenue_%"]
    .cumsum()
)

def abc_segment(x):
    if x <= 80:
        return "A"
    elif x <= 95:
        return "B"
    else:
        return "C"

product_revenue["Segment"] = (
    product_revenue["Cum_%"]
    .apply(abc_segment)
)

product_revenue.head()

         Product Name        Sales  Revenue_%     Cum_% Segment
133        Ionclotide  169083391.0   1.433033  1.433033       A
214        Tetratanyl  126091294.0   1.068662  2.501695       A
203        Sumanazole  113861431.0   0.965010  3.466705       A
61            Betanem  107073473.0   0.907480  4.374185       A
95   Docstryl Rivacin  103811886.0   0.879837  5.254023       A

In [ ]:
customer_sales = (
    df.groupby("Customer Name")["Sales"]
      .sum()
      .reset_index()
      .sort_values("Sales", ascending=False)
)

customer_sales["Revenue_%"] = (
    customer_sales["Sales"]
    / customer_sales["Sales"].sum()
    * 100
)

customer_sales["Cum_%"] = (
    customer_sales["Revenue_%"]
    .cumsum()
)

def abc_segment(x):
    if x <= 80:
        return "Platinum"
    elif x <= 95:
        return "Gold"
    else:
        return "Regular"


customer_sales["Segment"] = (
    customer_sales["Cum_%"]
    .apply(abc_segment)
)

customer_sales.to_csv("customer_sales.csv")

In [ ]:
rep_metrics = (
    df.groupby("Sales Rep")
      .agg({
          "Sales":"sum",
          "Quantity":"sum",
          "Customer Name":"nunique"
      })
      .reset_index()
)

rep_metrics.columns = [
    "Sales Rep",
    "Revenue",
    "Quantity",
    "Customers"
]
rep_metrics["Revenue_Score"] = (
    rep_metrics["Revenue"]
    / rep_metrics["Revenue"].max()
)

rep_metrics["Quantity_Score"] = (
    rep_metrics["Quantity"]
    / rep_metrics["Quantity"].max()
)

rep_metrics["Customer_Score"] = (
    rep_metrics["Customers"]
    / rep_metrics["Customers"].max()
)

In [ ]:
rep_metrics["Performance_Score"] = (
      0.5 * rep_metrics["Revenue_Score"]
    + 0.3 * rep_metrics["Quantity_Score"]
    + 0.2 * rep_metrics["Customer_Score"]
)

rep_metrics.sort_values(
    "Performance_Score",
    ascending=False
)

,Sales Rep,Revenue,Quantity,Customers,Revenue_Score,Quantity_Score,Customer_Score,Performance_Score
6,Jimmy Grey,9.859700e+08,2.293164e+06,751,1.000000,0.961684,1.0,0.988505
0,Abigail Thompson,9.810570e+08,2.301505e+06,751,0.995017,0.965182,1.0,0.987063
9,Sheila Stones,9.582039e+08,2.384530e+06,751,0.971839,1.000000,1.0,0.985919
3,Daniel Gates,9.506586e+08,2.310476e+06,751,0.964186,0.968944,1.0,0.972776
2,Anne Wu,9.201683e+08,2.230109e+06,751,0.933262,0.935240,1.0,0.947203
8,Morris Garcia,9.011955e+08,2.255844e+06,751,0.914019,0.946033,1.0,0.940819
11,Steve Pepple,8.754500e+08,2.237292e+06,751,0.887907,0.938253,1.0,0.925430
5,Jessica Smith,8.816984e+08,2.143427e+06,751,0.894245,0.898889,1.0,0.916789
10,Stella Given,8.883409e+08,2.109224e+06,751,0.900982,0.884545,1.0,0.915854
4,Erica Jones,8.713722e+08,2.137486e+06,751,0.883772,0.896397,1.0,0.910805
7,Mary Gerrard,8.752708e+08,2.111213e+06,751,0.887726,0.885379,1.0,0.909476
12,Thompson Crawford,8.669649e+08,2.098418e+06,751,0.879301,0.880013,1.0,0.903655
1,Alan Ray,8.426372e+08,2.066091e+06,751,0.854628,0.866456,1.0,0.887251

In [ ]:
city_sales = (
    df.groupby("City")["Sales"]
      .sum()
      .reset_index()
      .sort_values("Sales", ascending=False)
)

city_sales.head(20)

               City         Sales
96         Butzbach  9.356178e+07
40       Baesweiler  6.489050e+07
123        Cuxhaven  5.600668e+07
194       Friedberg  5.218363e+07
10        Altenburg  5.088532e+07
163       Emsdetten  4.593901e+07
77          Bottrop  4.445462e+07
191        Freising  4.377938e+07
646           Trier  4.349563e+07
105  Castrop-Rauxel  4.206666e+07
382         Limburg  4.151422e+07
52           Berlin  4.079679e+07
678           Wedel  4.046475e+07
142       Ditzingen  4.035582e+07
127          Dachau  3.793555e+07
155      Eberswalde  3.746560e+07
615         Springe  3.718111e+07
684        Weinheim  3.703776e+07
181     Filderstadt  3.676729e+07
136   Dessau-Roßlau  3.647921e+07

In [ ]:
geo_sales = (
    df.groupby(
        ["City","Latitude","Longitude"]
    )["Sales"]
    .sum()
    .reset_index()
)

geo_sales.head()

     City  Latitude  Longitude       Sales
0  Aachen   50.7762     6.0838  19090504.0
1   Aalen   48.8372    10.0936  13173562.0
2  Achern   48.6314     8.0739  21740500.0
3   Achim   53.0130     9.0330  18720448.0
4   Ahaus   52.0794     7.0134  18451676.0

In [ ]:
month_order = {
    "January":1,
    "February":2,
    "March":3,
    "April":4,
    "May":5,
    "June":6,
    "July":7,
    "August":8,
    "September":9,
    "October":10,
    "November":11,
    "December":12
}

monthly_sales = (
    df.groupby(["Year","Month"])["Sales"]
      .sum()
      .reset_index()
)

monthly_sales["Month_Num"] = monthly_sales["Month"].map(month_order)

monthly_sales = monthly_sales.sort_values(
    ["Year","Month_Num"]
)

monthly_sales["MoM_Growth_%"] = (
    monthly_sales["Sales"]
    .pct_change()
    * 100
)

# monthly_sales

In [ ]:
yearly_sales = (
    df.groupby("Year")["Sales"]
      .sum()
      .reset_index()
)

yearly_sales["YoY_Growth_%"] = (
    yearly_sales["Sales"]
    .pct_change()
    * 100
)

yearly_sales

   Year         Sales  YoY_Growth_%
0  2017  2.701481e+09           NaN
1  2018  3.506897e+09     29.813894
2  2019  2.930937e+09    -16.423641
3  2020  2.659672e+09     -9.255221

In [ ]:
pip install prophet

Requirement already satisfied: prophet in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (1.3.0)
Requirement already satisfied: cmdstanpy>=1.0.4 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from prophet) (1.3.0)
Requirement already satisfied: numpy>=1.15.4 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from prophet) (2.3.5)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from prophet) (3.10.8)
Requirement already satisfied: pandas>=1.0.4 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from prophet) (2.3.3)
Requirement already satisfied: holidays<1,>=0.25 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from prophet) (0.99)
Requirement already satisfied: tqdm>=4.36.1 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from prophet) (4.67.1)
Requirement already satisfied: importlib_resources in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from prophet) (7.1.0)
Requirement already satisfied: python-dateutil<3,>=2.9.0.post0 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from holidays<1,>=0.25->prophet) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from python-dateutil<3,>=2.9.0.post0->holidays<1,>=0.25->prophet) (1.17.0)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from cmdstanpy>=1.0.4->prophet) (0.5.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from matplotlib>=2.0.0->prophet) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from matplotlib>=2.0.0->prophet) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from matplotlib>=2.0.0->prophet) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from matplotlib>=2.0.0->prophet) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\karti\appdata\roaming\python\python311\site-packages (from matplotlib>=2.0.0->prophet) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from matplotlib>=2.0.0->prophet) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from matplotlib>=2.0.0->prophet) (3.3.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from pandas>=1.0.4->prophet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from pandas>=1.0.4->prophet) (2025.2)
Requirement already satisfied: colorama in c:\users\karti\anaconda3\envs\python_course\lib\site-packages (from tqdm>=4.36.1->prophet) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
forecast_df = (
    df.groupby(["Year","Month"])["Sales"]
      .sum()
      .reset_index()
)

forecast_df["ds"] = pd.to_datetime(
    forecast_df["Year"].astype(str)
    + "-"
    + forecast_df["Month"].astype(str)
    + "-01"
)

forecast_df.rename(
    columns={"Sales":"y"},
    inplace=True
)

forecast_df = forecast_df[["ds","y"]]

In [ ]:
from prophet import Prophet

model = Prophet()

model.fit(forecast_df)

future = model.make_future_dataframe(
    periods=12,
    freq="M"
)

forecast = model.predict(future)

forecast.tail()

c:\Users\karti\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Importing plotly failed. Interactive plots will not work.
22:57:33 - cmdstanpy - INFO - Chain [1] start processing
22:57:36 - cmdstanpy - INFO - Chain [1] done processing
c:\Users\karti\anaconda3\envs\python_course\Lib\site-packages\prophet\forecaster.py:1875: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range(

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
55,2021-07-31,2.296703e+08,4.855837e+08,6.044164e+08,2.296571e+08,2.296807e+08,3.156217e+08,3.156217e+08,3.156217e+08,3.156217e+08,3.156217e+08,3.156217e+08,0.0,0.0,0.0,5.452920e+08
56,2021-08-31,2.292231e+08,1.692766e+08,2.813796e+08,2.292075e+08,2.292357e+08,-5.066977e+06,-5.066977e+06,-5.066977e+06,-5.066977e+06,-5.066977e+06,-5.066977e+06,0.0,0.0,0.0,2.241561e+08
57,2021-09-30,2.287904e+08,1.880760e+08,3.019466e+08,2.287723e+08,2.288052e+08,1.452532e+07,1.452532e+07,1.452532e+07,1.452532e+07,1.452532e+07,1.452532e+07,0.0,0.0,0.0,2.433157e+08
58,2021-10-31,2.283432e+08,1.696714e+08,2.792009e+08,2.283224e+08,2.283603e+08,-3.485166e+06,-3.485166e+06,-3.485166e+06,-3.485166e+06,-3.485166e+06,-3.485166e+06,0.0,0.0,0.0,2.248580e+08
59,2021-11-30,2.279104e+08,1.043419e+08,2.155978e+08,2.278862e+08,2.279304e+08,-6.904254e+07,-6.904254e+07,-6.904254e+07,-6.904254e+07,-6.904254e+07,-6.904254e+07,0.0,0.0,0.0,1.588679e+08

In [ ]:
product_revenue.to_csv("product_segmentation.csv", index=False)

customer_sales.to_csv("customer_segmentation.csv", index=False)

rep_metrics.to_csv("rep_performance.csv", index=False)

forecast.to_csv("forecast.csv", index=False)

geo_sales.to_csv("geo_sales.csv", index=False)

monthly_sales.to_csv("monthly_sales.csv", index=False)

top_product_city.to_csv("top_product_city.csv", index=False)

In [ ]:
month_map = {
    'January':1,'February':2,'March':3,'April':4,
    'May':5,'June':6,'July':7,'August':8,
    'September':9,'October':10,'November':11,'December':12
}

df["Month_Num"] = df["Month"].map(month_map)

df["Date"] = pd.to_datetime(
    dict(
        year=df["Year"],
        month=df["Month_Num"],
        day=1
    )
)

In [ ]:
df.to_csv("pharma-data.csv")